export const CHARACTERS_UPDATE_CUSTOM_LIST = 'CHARACTERS_UPDATE_CUSTOM_LIST'
export const CHARACTERS_SET_CUSTOM_FETCHING = 'CHARACTERS_SET_CUSTOM_FETCHING'

export const CHARACTERS_UPDATE_LIST = 'CHARACTERS_UPDATE_LIST'
export const CHARACTERS_UPDATE_LIST_OFFSET = 'CHARACTERS_UPDATE_LIST_OFFSET'
export const CHARACTERS_SET_FETCHING = 'CHARACTERS_SET_FETCHING'

export const CHARACTERS_UPDATE_CHARACTER = 'CHARACTERS_UPDATE_CHARACTER'

// Character comic list
export const CHARACTERS_SET_CHARACTER_COMIC_LIST_FETCHING = 'CHARACTERS_SET_CHARACTER_COMIC_LIST_FETCHING'
export const CHARACTERS_UPDATE_CHARACTER_COMIC_LIST = 'CHARACTERS_UPDATE_CHARACTER_COMIC_LIST'
export const CHARACTERS_UPDATE_CHARACTER_COMIC_LIST_OFFSET = 'CHARACTERS_UPDATE_CHARACTER_COMIC_LIST_OFFSET'

export const CHARACTERS_UPDATE_EXTRA_EVENTS = 'CHARACTERS_UPDATE_EXTRA_EVENTS'
export const CHARACTERS_UPDATE_EXTRA_SERIES = 'CHARACTERS_UPDATE_EXTRA_SERIES'
export const CHARACTERS_UPDATE_EXTRA_STORIES = 'CHARACTERS_UPDATE_EXTRA_STORIES'